//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.4214
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWSAllocine.WSAlloCine {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FicheAllocine", Namespace="http://allocinews.org/")]
    [System.SerializableAttribute()]
    public partial class FicheAllocine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Titre {
            get {
                return this.TitreField;
            }
            set {
                if ((object.ReferenceEquals(this.TitreField, value) != true)) {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://allocinews.org/", ConfigurationName="WSAlloCine.ServiceAllocineSoap")]
    public interface ServiceAllocineSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d’élément HelloWorldResult de l’espace de noms http://allocinews.org/ n’est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://allocinews.org/HelloWorld", ReplyAction="*")]
        ClientWSAllocine.WSAlloCine.HelloWorldResponse HelloWorld(ClientWSAllocine.WSAlloCine.HelloWorldRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d’élément pCritere de l’espace de noms http://allocinews.org/ n’est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://allocinews.org/RechercheAllocine", ReplyAction="*")]
        ClientWSAllocine.WSAlloCine.RechercheAllocineResponse RechercheAllocine(ClientWSAllocine.WSAlloCine.RechercheAllocineRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://allocinews.org/", Order=0)]
        public ClientWSAllocine.WSAlloCine.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ClientWSAllocine.WSAlloCine.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://allocinews.org/", Order=0)]
        public ClientWSAllocine.WSAlloCine.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ClientWSAllocine.WSAlloCine.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://allocinews.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RechercheAllocineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RechercheAllocine", Namespace="http://allocinews.org/", Order=0)]
        public ClientWSAllocine.WSAlloCine.RechercheAllocineRequestBody Body;
        
        public RechercheAllocineRequest() {
        }
        
        public RechercheAllocineRequest(ClientWSAllocine.WSAlloCine.RechercheAllocineRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://allocinews.org/")]
    public partial class RechercheAllocineRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pCritere;
        
        public RechercheAllocineRequestBody() {
        }
        
        public RechercheAllocineRequestBody(string pCritere) {
            this.pCritere = pCritere;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RechercheAllocineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RechercheAllocineResponse", Namespace="http://allocinews.org/", Order=0)]
        public ClientWSAllocine.WSAlloCine.RechercheAllocineResponseBody Body;
        
        public RechercheAllocineResponse() {
        }
        
        public RechercheAllocineResponse(ClientWSAllocine.WSAlloCine.RechercheAllocineResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://allocinews.org/")]
    public partial class RechercheAllocineResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientWSAllocine.WSAlloCine.FicheAllocine[] RechercheAllocineResult;
        
        public RechercheAllocineResponseBody() {
        }
        
        public RechercheAllocineResponseBody(ClientWSAllocine.WSAlloCine.FicheAllocine[] RechercheAllocineResult) {
            this.RechercheAllocineResult = RechercheAllocineResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServiceAllocineSoapChannel : ClientWSAllocine.WSAlloCine.ServiceAllocineSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServiceAllocineSoapClient : System.ServiceModel.ClientBase<ClientWSAllocine.WSAlloCine.ServiceAllocineSoap>, ClientWSAllocine.WSAlloCine.ServiceAllocineSoap {
        
        public ServiceAllocineSoapClient() {
        }
        
        public ServiceAllocineSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAllocineSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAllocineSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAllocineSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWSAllocine.WSAlloCine.HelloWorldResponse ClientWSAllocine.WSAlloCine.ServiceAllocineSoap.HelloWorld(ClientWSAllocine.WSAlloCine.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ClientWSAllocine.WSAlloCine.HelloWorldRequest inValue = new ClientWSAllocine.WSAlloCine.HelloWorldRequest();
            inValue.Body = new ClientWSAllocine.WSAlloCine.HelloWorldRequestBody();
            ClientWSAllocine.WSAlloCine.HelloWorldResponse retVal = ((ClientWSAllocine.WSAlloCine.ServiceAllocineSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWSAllocine.WSAlloCine.RechercheAllocineResponse ClientWSAllocine.WSAlloCine.ServiceAllocineSoap.RechercheAllocine(ClientWSAllocine.WSAlloCine.RechercheAllocineRequest request) {
            return base.Channel.RechercheAllocine(request);
        }
        
        public ClientWSAllocine.WSAlloCine.FicheAllocine[] RechercheAllocine(string pCritere) {
            ClientWSAllocine.WSAlloCine.RechercheAllocineRequest inValue = new ClientWSAllocine.WSAlloCine.RechercheAllocineRequest();
            inValue.Body = new ClientWSAllocine.WSAlloCine.RechercheAllocineRequestBody();
            inValue.Body.pCritere = pCritere;
            ClientWSAllocine.WSAlloCine.RechercheAllocineResponse retVal = ((ClientWSAllocine.WSAlloCine.ServiceAllocineSoap)(this)).RechercheAllocine(inValue);
            return retVal.Body.RechercheAllocineResult;
        }
    }
}
